version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix: "
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix: "
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      devcontainers:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/collector"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix: "
    groups:
      uv-collector:
        patterns:
          - "*"
