name: Create Release, Build and Deploy Image

on:
  push:
    branches:
      - "main"

permissions:
  actions: write
  contents: write
  issues: write
  id-token: write
  pull-requests: write

jobs:
  build-and-release-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-and-push-image.yml@5f38a9b813cea2d0b872138c064aa7e39d481995 # v1.0.3
    secrets: inherit
