name: Build Image on PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-image-pr.yml@5f38a9b813cea2d0b872138c064aa7e39d481995 # v1.0.3
